#!/usr/bin/env python
# coding=utf-8

from matrices import *
from lists import *
import cProfile
import re
import time

# Measuring how long a script runs
start = time.time()

X = [[12,7],
    [4 ,5],
    [3 ,8]]


# List tests
print("\n*************************** Lists *************************************\n")
n = 100
print(empty_list(n))
print(random_list(n))
print(mult_lists([3,4],[2,3]))
print(expandByN([3,4,5], 5))
print(sum_lists([3,4],[2,3]))
print("*************************** Lists *************************************")

# Matrix tests
print("\n*************************** Matrices *************************************\n")
n = 10
m = 10
print_matrix(empty_matrix(5,4))
print_matrix(random_matrix(5,4))
print_matrix(identity_matrix(5))
print_matrix(transpose(X))
print_matrix(mult_matrix(X, identity_matrix(2)))
print_matrix(sum_matrix(X,X))
print(matrix2list(X))
print(matrix2list(identity_matrix(5)))
print_matrix(list2matrix(expandByN([3,4,5], 5)))

print("*************************** Matrices *************************************")

print("\n*************************** cProfile *************************************\n")
# Measures the function calls to the given function in the string
cProfile.run('transpose("X")')
print("*************************** cProfile *************************************")

print('Script took', time.time()-start, 'seconds.')