#!/usr/bin/env python
# coding=utf-8
import sys
import os.path
import argparse
import time
import list_tests
import matrix_tests
import stack_tests
import threading
import subprocess
import inspect
from threading import Thread
import multiprocessing
from parse import parse

def run_test(test, size = None, iterations = None):
	global running
	running = True
	# Measuring how long a script runs
	start = time.time()
	if size == None:
		if iterations == None:
			test()
		else:
			test(n = iterations)
	else:
		if iterations == None:
			test(size = size)
		else:
			test(iterations,size)
	print test.__name__, 'took', time.time()-start, 'seconds.'
	running = False
	return

def cache_info(architecture, cores, struct, test, size, iterations, worker_id):
	directory = '../logs/'+ architecture + '/' + struct + '_cache/test_' + str(test)
	if not os.path.exists(directory):
		os.makedirs(directory)
	n = 1
	while os.path.exists('../logs/'+ architecture + '/' + struct + '_cache/test_' + str(test) + '/' + str(cores) + '_cores_'  + str(iterations) + '_' + str(size) + '_' + str(worker_id) + "_" + str(n) + '.log'):
		n += 1
	path = '../logs/'+ architecture + '/' + struct + '_cache/test_' + str(test) + '/' + str(cores) + '_cores_'  + str(iterations) + '_' + str(size) + '_' + str(worker_id) + "_" + str(n) + '.log'
	print ("Saving log at: " + path)
	log = open(path, 'a')  # so that data written to it will be appended
	log.flush()
	cache = subprocess.Popen(['date +"%Y-%m-%d %H:%M:%S:%3N"; lscpu | grep "cache"; echo'], stdout=log, stderr=log, shell=True)
	cache.wait()
	log.flush()
	time.sleep(1)
	with open('flags_parsed.txt') as f:
	    content = f.readlines()
	perf_flags = content[0]
	while running:
		log.flush()
		command = 'date +"%Y-%m-%d %H:%M:%S:%3N"; timeout -s 2 --preserve-status 1s perf stat -e ' + perf_flags + ' -p ' + str(os.getpid()) + ' -x ,'
		#cache = subprocess.Popen(['date +"%Y-%m-%d %H:%M:%S:%3N"; lscpu | grep "cache"; cat /proc/meminfo | grep "Cached"; echo'], stdout=log, stderr=log, shell=True)
		cache = subprocess.Popen([command], stdout=log, stderr=log, shell=True)
		cache.wait()
		log.flush()
		time.sleep(10)
	log.close()
	parse(path, path+'.csv', delimeter=',', r = True, n = 83, ignore = 6)
	return

# starts work at a core and keeps track of overall cores being used, size of structure, and # of iterations
def worker(worker_id, architecture, cores, struct, test = None, iterations = None, size = None):
    #worker function
    if struct == 'matrices':
    	tests = matrix_tests.tests
    elif struct == 'lists':
    	tests = list_tests.tests
    elif struct == 'stack':
    	tests = stack_tests.tests
    else:
    	raise ValueError("Please choose a set of test(s) to run.")

    print("testing",test)

    if test == None:
    	for i in range(len(tests)):
    		defaults =  inspect.getargspec(tests[i])[3]
    		if iterations == None:
    			n = defaults[0] / 100 # temp
    		else:
    			n = iterations
    		if size == None:
    			s = defaults[1]
    		else:
    			s = size
    		script = Thread(target = run_test, args = [tests[i],s,n])
    		cache = Thread(target = cache_info, args = [architecture, cores, struct, i+1,s,n, worker_id])
    		script.start()
    		cache.start()
    		script.join()
    		cache.join()
    else:
    	defaults =  inspect.getargspec(tests[test-1])[3]
    	if iterations == None:
    		n = defaults[0]  / 100 # temp
    	else:
    		n = iterations
    	if size == None:
    		s = defaults[1]
    	else:
    		s = size
    	script = Thread(target = run_test, args = [tests[test-1],size,iterations])
    	cache = Thread(target = cache_info, args = [architecture, cores, struct, test,s,n, worker_id])
    	script.start()
    	cache.start()
    	script.join()
    	cache.join()

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument("-t", "--test", type=int, help="Which test to run, default runs all tests available")
	parser.add_argument("-c", "--cores", type=int, help="The number of cores to use, default c=Number of available CPUs in architecture")
	parser.add_argument("-a", "--architecture", type=str, help="The name of the architecture being benchmarked, for log purposes [REQUIRED]")
	parser.add_argument("-s", "--struct", type=str, help="Which structure to use for benchmarking, e.g. tests using lists, matrices, stack... default s=lists")
	parser.add_argument("-si", "--size", type=int, help="The size of the struct to use, or for stack, to which fibonacci to calculate.")
	parser.add_argument("-i", "--iterations", type=int, help="The number of iterations to run the test for")
	args = parser.parse_args()

	architecture = ''
	struct = 'lists'
	n_test = None
	cores = multiprocessing.cpu_count()
	iterations = None
	size = None
	
	if not(args.architecture == None):
		architecture = args.architecture
	else:
		raise ValueError("Need to specify which architecture is being used.")
	if not(args.struct == None):
		struct = args.struct
	if not(args.test == None):
		n_test = args.test
	if not(args.cores == None):
		cores = args.cores
	if not(args.iterations == None):
		iterations = args.iterations
	if not(args.size == None):
		size = args.size

	# Measuring how long a script runs
	start = time.time()
	# turning off watchdog to allow for cache flags
	watchdog = subprocess.Popen(['sudo sh -c "echo \'0\' > /proc/sys/kernel/nmi_watchdog"'], shell=True)
	watchdog.wait()
	# changing perf privileges to allow use of controls of the performance events system
	perf = subprocess.Popen(['sudo sh -c "echo \'-1\' > /proc/sys/kernel/perf_event_paranoid"'], shell=True)
	perf.wait()
	time.sleep(1)
	jobs = []
	for i in range(cores):
		p = multiprocessing.Process(target=worker, args = (i, architecture, cores, struct, n_test, size, iterations))
		jobs.append(p)
		p.start()
	while True:
	    if any(process.is_alive() for process in jobs):
	        time.sleep(1)
	    else:
	    	# turning watchdog back on
	    	watchdog = subprocess.Popen(['sudo sh -c "echo \'1\' > /proc/sys/kernel/nmi_watchdog"'], shell=True)
	    	watchdog.wait()
	    	# removing hanging perf privileges to disallow use of controls of the performance events system
	    	perf = subprocess.Popen(['sudo sh -c "echo \'3\' > /proc/sys/kernel/perf_event_paranoid"'], shell=True)
	    	perf.wait()
	    	time.sleep(1)
	    	print('All processes done')
	    	print 'Script took', time.time()-start, 'seconds.'
	    	break